### ISSUE TITLE
`rake` is required although it's listed as dev dependency

### ISSUE THREAD

**Issue by igor-starostenko** [p0deje/yard-doctest#8]
Hi,

I'm getting an error when running `yard doctest`:
```
[error]: Error loading plugin 'yard-doctest'
...
```
Because I don't have `rake` installed in my project.

In [gemspec](https://github.com/p0deje/yard-doctest/blob/4c30091c9d145a6601f18467258031f3b34844ab/yard-doctest.gemspec#L24) rake is listed as dev dependency, although in [yard-doctest.rb](https://github.com/p0deje/yard-doctest/blob/4c30091c9d145a6601f18467258031f3b34844ab/lib/yard-doctest.rb#L7) it requires rake.

To fix it `rake` should either be listed as a runtime dependency or be removed from `yard-doctest.rb` and only loaded directly from `Rakefile`

Thanks for the awesome gem 👍

**Comment by p0deje** [comment]
Thank you for the bug report! I've changed so that now it doesn't load Rake tasks automatically and you need to add `require 'yard/doctest/rake'` to your Rakefile if you want to use them.
